# Generated by Django 4.2 on 2025-06-04 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='response',
            field=models.TextField(default='Pas de réponse'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
